import '../styles/custom.scss';
import "../styles/globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';


export const metadata = {
  title: "Dalat Accesibilidad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
